# Generated by Django 4.0.4 on 2022-05-30 09:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import report.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('hausnummer', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=50)),
                ('bild', models.FileField(upload_to=report.models._building_file)),
                ('karte', models.FileField(upload_to=report.models._building_file)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.CharField(max_length=5, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^[A-Z]{1}\\d{4}', 'not a valid kgs id')])),
                ('name', models.CharField(max_length=50)),
                ('gemeinde', models.CharField(max_length=30)),
                ('plz', models.IntegerField()),
                ('ort', models.CharField(max_length=40, validators=[django.core.validators.RegexValidator('^\\w+$', 'Nur den Strassennamen eingeben!')])),
                ('strasse', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^\\w+$', 'Nur den Strassennamen eingeben!')])),
                ('koordinaten', models.CharField(max_length=40)),
                ('bild', models.FileField(upload_to=report.models._location_file)),
                ('karte', models.FileField(upload_to=report.models._location_file)),
                ('aufgenommen_am', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('karte', models.FileField(upload_to=report.models._room_file)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.building')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.location')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.CharField(max_length=5, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^[A-Z]{1}\\d{4}', 'not a valid kgs id')])),
                ('name', models.CharField(max_length=50)),
                ('aufgenommen_am', models.DateField()),
                ('lage', models.CharField(blank=True, max_length=50)),
                ('priority', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default=5, max_length=2)),
                ('beschreibung', models.TextField()),
                ('hoehe', models.CharField(max_length=50)),
                ('laenge', models.CharField(max_length=50)),
                ('breite', models.CharField(max_length=50)),
                ('feuer', models.BooleanField()),
                ('wasser', models.BooleanField()),
                ('gewalt', models.BooleanField()),
                ('schmutz', models.BooleanField()),
                ('massnahmen', models.TextField()),
                ('personal', models.CharField(max_length=100)),
                ('material', models.TextField(blank=True)),
                ('evakuation', models.TextField(blank=True)),
                ('plan', models.FileField(upload_to=report.models._item_file)),
                ('bild', models.FileField(upload_to=report.models._item_file)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.building')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.location')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.room')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('vorname', models.CharField(max_length=50)),
                ('nachname', models.CharField(max_length=50)),
                ('strasse', models.CharField(max_length=50)),
                ('hausnummer', models.CharField(max_length=5)),
                ('plz', models.IntegerField()),
                ('email', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=10)),
                ('bemerkungen', models.TextField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.location')),
            ],
        ),
        migrations.AddField(
            model_name='building',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.location'),
        ),
    ]
