# Generated by Django 4.0.4 on 2022-05-31 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_rename_laenge_item_tiefe_alter_contact_bemerkungen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='priority',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=5, max_length=1),
        ),
    ]
